#
#   General Site Settigns
#
author: Alberto Silva
title: Front End Developer
email: asilvadesigns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#
#   General Build Settings
#
#   Url
baseurl: "/albertosilvame"     # remote
#baseurl: ""                     # local
url: ""                         # the base hostname & protocol for your site
imagepath: "/images/"
projectimagepath: "/images/projects/"
permalink: pretty

#   Exclue files and directories
exclude:
    - LICENSE
    - README.md
    - gulpfile.js
    - node_modules
    - package.json

#   Output specified collections
collections:
    projects:
        output: true

#   Set collection default layout
defaults:
    - scope:
        type: projects
      values:
        layout: project
